import Head from 'next/head'
import conectarDB from '@/lib/dbConnect'
import Movie from '@/models/Movie'
import Link from 'next/link'

export default function Home({movies}) {
  console.log(movies)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <h1>Movies</h1>
        <Link className='btn btn-primary w-100' href="/new">
          Agregar
        </Link>
        {
          movies.map(({_id, tittle, plot}) => (
              <div className="card mb-2 my-2" key={_id}>{
                <div className="card-body">
                  <div className="h5 text-uppercase">{tittle}</div>
                  <p className="fw-light">{plot}</p>
                  <Link href={`/${_id}`} className="btn btn-success btn-sm me-2">
                     Más info...
                  </Link>

                  
                </div>
              }</div>
          ))
        }
      </main>
    </div>
  )
}

export async function getServerSideProps(){
  try {
    await conectarDB()

    const res = await Movie.find({})

    const movies = res.map(doc => {
      const movie = doc.toObject()
      movie._id = `${movie._id}`   //Puede ser movie._id = movie._id.toString
      return movie
    })

   // console.log(res)

    return {props: {movies}}
  } catch (error) {
    console.log(error)
  }
}
